//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::file_chunks::Entity as FileChunks;
pub use super::files::Entity as Files;
pub use super::index_tasks::Entity as IndexTasks;
pub use super::searches::Entity as Searches;
